WIP: Streaming support helpers.
capnproto/go-capnproto2 pull request #450
Opened 2023-02-12 03:27 UTC by zenhack

This patch begins work on ergonomic improvements to streaming workflows. The plan is to update the code generator to use SendStreamingCall for methods whose return type is stream, and have them similarly just return streamError instead of a result, release pair. This lets the caller just invoke the method in a loop and check the error each time through (or only at the end on a done() method or the like if they don't care about short-circuiting).

---

@lthibault this is untested, but I wanted to get your thoughts on the design before putting too much more work on this.

2023-02-12 04:11 UTC, lthibault requested changes

2023-02-12 04:11 UTC, lthibault commented on capability.go
> +//    client will reutrn the same error. (without starting
Typos: "retrun" & period before parentheses.

2023-02-12 04:13 UTC, lthibault commented
The general direction looks good to me. At some point, it might be worthwhile to use a queue of some sort and avoid forking a goroutine on each call, but no need to worry about that yet.

2023-02-12 05:20 UTC, zenhack commented
Testing has revealed that as-written this doesn't work as I intended; there's a race where if your final call to done() or whatever goes out before the first error comes back in, you never see the error. I could try to rework things such that other calls actually check for errors on prior calls, but that seems messy; what if we just required the user to call a separate:

```
func (c Client) WaitStreaming(ctx context.Context) error
```
...which would wait for all outstanding streaming calls to settle (or for one to return an error), and then return the first error? So the pattern would be:

1. Make all your streaming calls. Check errors only if you care about short-circuiting.
2. Maybe call a Done() method or the like if that's part of your interface's contract.
3. Call WaitStreaming() to check if any of the streaming methods errored.

This seems like it would be much easier to implement than trying to instrument returned futures and the like, and it has the upside that it's now possible to distinguish between done() failing and a streaming call failing, though I'm not sure that's something that's likely to be needed.

Thoughts?

2023-02-13 13:31 UTC, lthibault commented
The `WaitStreaming` method and its associated pattern is analogous to how I've been doing streaming calls on the application side, so I'm onboard.  For what it's worth, I've found it convenient to write loops that look like the following:

```go
for stream.Open() {  // short-circuit?
    stream.DoTheThing(...)
}

if stream.Err() != nil {
    return stream.Err()
}
```

2023-02-13 23:46 UTC, zenhack commented
Great. Modulo further feedback, this is done.

2023-02-13 23:53 UTC, lthibault commented on capability.go
> +				c.streamWg = &sync.WaitGroup{}
Is there a reason for this lazy initialization, as opposed to removing the pointer indirection on `streamWg`?

2023-02-13 23:53 UTC, lthibault commented on capability.go
> +	wg.Wait()
It seems like a lot of this logic could be abstracted away with `errgroup.Group`.  I'm fairly certain the zero-value `Group` will behave correctly, here.

Also, now that I think of it, shouldn't any outstanding calls to a streaming capability immediately fail if a previous call fails?  It seems like `errgroup.WithContext` could help with this.

2023-02-14 00:24 UTC, lthibault commented on capability.go
> +		return ErrorAnswer(s.Method, exc.WrapError("stream error", c.stream.err)), func() {}
Do we need to hold the lock to access `c.stream.err`?

2023-02-14 00:31 UTC, lthibault approved these changes

2023-02-14 01:12 UTC, merged